source 'https://rubygems.org'
source 'https://gem.fury.io/engineerai'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.6.5'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 6.0.3', '>= 6.0.3.6'
# Use postgresql as the database for Active Record
gem 'pg', '>= 0.18', '< 2.0'
# Use Puma as the app server
gem 'puma', '~> 4.1'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
# gem 'jbuilder', '~> 2.7'
# Use Active Model has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Active Storage variant
# gem 'image_processing', '~> 1.2'

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin AJAX possible
# gem 'rack-cors'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
end

group :development do
  gem 'dotenv-rails'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
gem 'bx_block_push_notifications-c0f9e9b7', '0.0.7', require: 'bx_block_push_notifications'
gem 'bx_block_settings-5412d427', '0.0.3', require: 'bx_block_settings'
gem 'bx_block_catalogue-0e5da613', '0.0.6', require: 'bx_block_catalogue'
gem 'bx_block_upload_media-9de56634', '0.0.2', require: 'bx_block_upload_media'
gem 'bx_block_data_import_export_csv-ec567cbb', '0.0.2', require: 'bx_block_data_import_export_csv'
gem 'bx_block_forgot_password-4de8968b', '0.0.6', require: 'bx_block_forgot_password'
gem 'bx_block_payment_admin', '0.0.2'
gem 'account_block', '0.0.29'
gem 'bx_block_photo_library-6419d914', '0.0.2', require: 'bx_block_photo_library'
gem 'bx_block_order_management-674a3e38', '0.0.5', require: 'bx_block_order_management'
gem 'bx_block_roles_permissions-c50949d0', '0.0.6', require: 'bx_block_roles_permissions'
gem 'bx_block_posts-3dc5b993', '0.0.12', require: 'bx_block_posts'
gem 'bx_block_admin', '0.0.10'
gem 'bx_block_advanced_search-23b25188', '0.0.2', require: 'bx_block_advanced_search'
gem 'bx_block_email_notifications', '0.0.3'
gem 'builder_base', '0.0.43'
gem 'sassc-rails'
gem 'activeadmin'
gem 'active_admin_role'
gem 'activeadmin_json_editor'
gem 'active_admin_datetimepicker'
gem 'sidekiq_alive'
gem 'sidekiq', '~> 6.1.0'
gem "yabeda-prometheus"    # Base
gem "yabeda-rails"         #API endpoint monitoring
gem "yabeda-http_requests" #External request monitoring
gem "yabeda-puma-plugin"
gem 'yabeda-sidekiq'
gem 'bx_block_cors'
gem 'arctic_admin'
gem "letter_opener", group: :development
gem 'city-state'
# gem 'country_state_select'