---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-deploy-extd-config
  labels:
    app: "{{ template "app-deploy.fullname" . }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation
data:
{{- with .Values.appExtConfig }}
  {{- toYaml . | nindent 2 }}
{{- end }}
