{{- if .Values.railsMigration.enabled -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: db-migration
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  backoffLimit: {{ .Values.railsMigration.retry }}
  activeDeadlineSeconds: {{ .Values.railsMigration.timeout }}
  template:
    metadata:
      name: db-migration
    spec: 
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: db-migration
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        command:
          - bundle
          - exec
          - rails
          - db:migrate
          - db:seed
        envFrom:
          - secretRef:
              name: app-secrets
          - configMapRef:
              name: app-deploy-extd-config
              optional: true
      restartPolicy: Never
{{- end -}}
