{{- if .Values.railsSidekiq.enabled -}}
{{- if .Capabilities.APIVersions.Has "autoscaling.k8s.io/v1beta2/VerticalPodAutoscaler" -}}
apiVersion: "autoscaling.k8s.io/v1beta2"
kind: VerticalPodAutoscaler
metadata:
  name: {{ include "app-deploy.fullname" . }}-sidekiq
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "app-deploy.fullname" . }}-sidekiq
  updatePolicy:
    updateMode: "Off"
  resourcePolicy:
    containerPolicies:
      - containerName: '*'
        minAllowed:
          cpu: 10m
          memory: 50Mi
        maxAllowed:
          cpu: 1
          memory: 1Gi
        controlledResources: ["cpu", "memory"]
{{- end -}}
{{- end -}}